// A curated set of 500 basic Japanese words (JLPT N5/N4-ish vocabulary),
// spelled in pure hiragana (no kanji, no katakana loanwords) so every word
// works with the tile-spelling mechanic in Words mode.
export interface JapaneseWord {
  hiragana: string
  romaji: string
  english: string
}

export const WORDS: JapaneseWord[] = [
  { hiragana: 'こんにちは', romaji: 'konnichiwa', english: 'hello' },
  { hiragana: 'おはよう', romaji: 'ohayou', english: 'good morning' },
  { hiragana: 'こんばんは', romaji: 'konbanwa', english: 'good evening' },
  { hiragana: 'さようなら', romaji: 'sayounara', english: 'goodbye' },
  { hiragana: 'ありがとう', romaji: 'arigatou', english: 'thank you' },
  { hiragana: 'すみません', romaji: 'sumimasen', english: 'excuse me' },
  { hiragana: 'はい', romaji: 'hai', english: 'yes' },
  { hiragana: 'いいえ', romaji: 'iie', english: 'no' },
  { hiragana: 'おやすみ', romaji: 'oyasumi', english: 'good night' },
  { hiragana: 'いってきます', romaji: 'ittekimasu', english: 'I\'m off' },
  { hiragana: 'いってらっしゃい', romaji: 'itterasshai', english: 'see you off' },
  { hiragana: 'ただいま', romaji: 'tadaima', english: 'I\'m home' },
  { hiragana: 'おかえり', romaji: 'okaeri', english: 'welcome home' },
  { hiragana: 'おねがいします', romaji: 'onegaishimasu', english: 'please' },
  { hiragana: 'どうぞ', romaji: 'douzo', english: 'go ahead' },
  { hiragana: 'げんき', romaji: 'genki', english: 'healthy' },
  { hiragana: 'はじめまして', romaji: 'hajimemashite', english: 'nice to meet you' },
  { hiragana: 'おめでとう', romaji: 'omedetou', english: 'congratulations' },
  { hiragana: 'だいじょうぶ', romaji: 'daijoubu', english: 'okay' },
  { hiragana: 'わかりました', romaji: 'wakarimashita', english: 'understood' },
  { hiragana: 'いち', romaji: 'ichi', english: 'one' },
  { hiragana: 'に', romaji: 'ni', english: 'two' },
  { hiragana: 'さん', romaji: 'san', english: 'three' },
  { hiragana: 'よん', romaji: 'yon', english: 'four' },
  { hiragana: 'ご', romaji: 'go', english: 'five' },
  { hiragana: 'ろく', romaji: 'roku', english: 'six' },
  { hiragana: 'なな', romaji: 'nana', english: 'seven' },
  { hiragana: 'はち', romaji: 'hachi', english: 'eight' },
  { hiragana: 'きゅう', romaji: 'kyuu', english: 'nine' },
  { hiragana: 'じゅう', romaji: 'juu', english: 'ten' },
  { hiragana: 'ひゃく', romaji: 'hyaku', english: 'hundred' },
  { hiragana: 'せん', romaji: 'sen', english: 'thousand' },
  { hiragana: 'まん', romaji: 'man', english: 'ten thousand' },
  { hiragana: 'ひとつ', romaji: 'hitotsu', english: 'one (thing)' },
  { hiragana: 'ふたつ', romaji: 'futatsu', english: 'two (things)' },
  { hiragana: 'みっつ', romaji: 'mittsu', english: 'three (things)' },
  { hiragana: 'よっつ', romaji: 'yottsu', english: 'four (things)' },
  { hiragana: 'いつつ', romaji: 'itsutsu', english: 'five (things)' },
  { hiragana: 'むっつ', romaji: 'muttsu', english: 'six (things)' },
  { hiragana: 'ななつ', romaji: 'nanatsu', english: 'seven (things)' },
  { hiragana: 'やっつ', romaji: 'yattsu', english: 'eight (things)' },
  { hiragana: 'ここのつ', romaji: 'kokonotsu', english: 'nine (things)' },
  { hiragana: 'とお', romaji: 'too', english: 'ten (things)' },
  { hiragana: 'はんぶん', romaji: 'hanbun', english: 'half' },
  { hiragana: 'ぜんぶ', romaji: 'zenbu', english: 'all' },
  { hiragana: 'きょう', romaji: 'kyou', english: 'today' },
  { hiragana: 'あした', romaji: 'ashita', english: 'tomorrow' },
  { hiragana: 'きのう', romaji: 'kinou', english: 'yesterday' },
  { hiragana: 'あさ', romaji: 'asa', english: 'morning' },
  { hiragana: 'ひる', romaji: 'hiru', english: 'noon' },
  { hiragana: 'よる', romaji: 'yoru', english: 'night' },
  { hiragana: 'ばん', romaji: 'ban', english: 'evening' },
  { hiragana: 'いま', romaji: 'ima', english: 'now' },
  { hiragana: 'まいにち', romaji: 'mainichi', english: 'every day' },
  { hiragana: 'しゅうまつ', romaji: 'shuumatsu', english: 'weekend' },
  { hiragana: 'げつようび', romaji: 'getsuyoubi', english: 'Monday' },
  { hiragana: 'かようび', romaji: 'kayoubi', english: 'Tuesday' },
  { hiragana: 'すいようび', romaji: 'suiyoubi', english: 'Wednesday' },
  { hiragana: 'もくようび', romaji: 'mokuyoubi', english: 'Thursday' },
  { hiragana: 'きんようび', romaji: 'kinyoubi', english: 'Friday' },
  { hiragana: 'どようび', romaji: 'doyoubi', english: 'Saturday' },
  { hiragana: 'にちようび', romaji: 'nichiyoubi', english: 'Sunday' },
  { hiragana: 'らいねん', romaji: 'rainen', english: 'next year' },
  { hiragana: 'きょねん', romaji: 'kyonen', english: 'last year' },
  { hiragana: 'ことし', romaji: 'kotoshi', english: 'this year' },
  { hiragana: 'まいあさ', romaji: 'maiasa', english: 'every morning' },
  { hiragana: 'まいばん', romaji: 'maiban', english: 'every night' },
  { hiragana: 'いつも', romaji: 'itsumo', english: 'always' },
  { hiragana: 'ときどき', romaji: 'tokidoki', english: 'sometimes' },
  { hiragana: 'じかん', romaji: 'jikan', english: 'time' },
  { hiragana: 'ふん', romaji: 'fun', english: 'minute' },
  { hiragana: 'びょう', romaji: 'byou', english: 'second' },
  { hiragana: 'つき', romaji: 'tsuki', english: 'month' },
  { hiragana: 'しゅう', romaji: 'shuu', english: 'week' },
  { hiragana: 'とし', romaji: 'toshi', english: 'year' },
  { hiragana: 'せんげつ', romaji: 'sengetsu', english: 'last month' },
  { hiragana: 'らいげつ', romaji: 'raigetsu', english: 'next month' },
  { hiragana: 'こんげつ', romaji: 'kongetsu', english: 'this month' },
  { hiragana: 'せんしゅう', romaji: 'senshuu', english: 'last week' },
  { hiragana: 'らいしゅう', romaji: 'raishuu', english: 'next week' },
  { hiragana: 'こんしゅう', romaji: 'konshuu', english: 'this week' },
  { hiragana: 'けさ', romaji: 'kesa', english: 'this morning' },
  { hiragana: 'こんばん', romaji: 'konban', english: 'tonight' },
  { hiragana: 'あか', romaji: 'aka', english: 'red' },
  { hiragana: 'あお', romaji: 'ao', english: 'blue' },
  { hiragana: 'きいろ', romaji: 'kiiro', english: 'yellow' },
  { hiragana: 'みどり', romaji: 'midori', english: 'green' },
  { hiragana: 'しろ', romaji: 'shiro', english: 'white' },
  { hiragana: 'くろ', romaji: 'kuro', english: 'black' },
  { hiragana: 'ちゃいろ', romaji: 'chairo', english: 'brown' },
  { hiragana: 'むらさき', romaji: 'murasaki', english: 'purple' },
  { hiragana: 'だいだいいろ', romaji: 'daidaiiro', english: 'orange' },
  { hiragana: 'はいいろ', romaji: 'haiiro', english: 'gray' },
  { hiragana: 'きんいろ', romaji: 'kin\'iro', english: 'gold' },
  { hiragana: 'ぎんいろ', romaji: 'gin\'iro', english: 'silver' },
  { hiragana: 'かぞく', romaji: 'kazoku', english: 'family' },
  { hiragana: 'おとうさん', romaji: 'otousan', english: 'father' },
  { hiragana: 'おかあさん', romaji: 'okaasan', english: 'mother' },
  { hiragana: 'おにいさん', romaji: 'oniisan', english: 'older brother' },
  { hiragana: 'おねえさん', romaji: 'oneesan', english: 'older sister' },
  { hiragana: 'おとうと', romaji: 'otouto', english: 'younger brother' },
  { hiragana: 'いもうと', romaji: 'imouto', english: 'younger sister' },
  { hiragana: 'こども', romaji: 'kodomo', english: 'child' },
  { hiragana: 'あかちゃん', romaji: 'akachan', english: 'baby' },
  { hiragana: 'そふ', romaji: 'sofu', english: 'grandfather' },
  { hiragana: 'そぼ', romaji: 'sobo', english: 'grandmother' },
  { hiragana: 'おじいさん', romaji: 'ojiisan', english: 'grandpa' },
  { hiragana: 'おばあさん', romaji: 'obaasan', english: 'grandma' },
  { hiragana: 'おじさん', romaji: 'ojisan', english: 'uncle' },
  { hiragana: 'おばさん', romaji: 'obasan', english: 'aunt' },
  { hiragana: 'むすこ', romaji: 'musuko', english: 'son' },
  { hiragana: 'むすめ', romaji: 'musume', english: 'daughter' },
  { hiragana: 'つま', romaji: 'tsuma', english: 'wife' },
  { hiragana: 'おっと', romaji: 'otto', english: 'husband' },
  { hiragana: 'りょうしん', romaji: 'ryoushin', english: 'parents' },
  { hiragana: 'ふうふ', romaji: 'fuufu', english: 'married couple' },
  { hiragana: 'まご', romaji: 'mago', english: 'grandchild' },
  { hiragana: 'あたま', romaji: 'atama', english: 'head' },
  { hiragana: 'かお', romaji: 'kao', english: 'face' },
  { hiragana: 'め', romaji: 'me', english: 'eye' },
  { hiragana: 'みみ', romaji: 'mimi', english: 'ear' },
  { hiragana: 'はな', romaji: 'hana', english: 'nose' },
  { hiragana: 'くち', romaji: 'kuchi', english: 'mouth' },
  { hiragana: 'は', romaji: 'ha', english: 'tooth' },
  { hiragana: 'くび', romaji: 'kubi', english: 'neck' },
  { hiragana: 'かた', romaji: 'kata', english: 'shoulder' },
  { hiragana: 'うで', romaji: 'ude', english: 'arm' },
  { hiragana: 'て', romaji: 'te', english: 'hand' },
  { hiragana: 'ゆび', romaji: 'yubi', english: 'finger' },
  { hiragana: 'むね', romaji: 'mune', english: 'chest' },
  { hiragana: 'おなか', romaji: 'onaka', english: 'stomach' },
  { hiragana: 'あし', romaji: 'ashi', english: 'leg' },
  { hiragana: 'ひざ', romaji: 'hiza', english: 'knee' },
  { hiragana: 'せなか', romaji: 'senaka', english: 'back' },
  { hiragana: 'かみ', romaji: 'kami', english: 'hair' },
  { hiragana: 'からだ', romaji: 'karada', english: 'body' },
  { hiragana: 'こころ', romaji: 'kokoro', english: 'heart' },
  { hiragana: 'いぬ', romaji: 'inu', english: 'dog' },
  { hiragana: 'ねこ', romaji: 'neko', english: 'cat' },
  { hiragana: 'とり', romaji: 'tori', english: 'bird' },
  { hiragana: 'さかな', romaji: 'sakana', english: 'fish' },
  { hiragana: 'うま', romaji: 'uma', english: 'horse' },
  { hiragana: 'うし', romaji: 'ushi', english: 'cow' },
  { hiragana: 'ぶた', romaji: 'buta', english: 'pig' },
  { hiragana: 'ひつじ', romaji: 'hitsuji', english: 'sheep' },
  { hiragana: 'やぎ', romaji: 'yagi', english: 'goat' },
  { hiragana: 'ねずみ', romaji: 'nezumi', english: 'mouse' },
  { hiragana: 'うさぎ', romaji: 'usagi', english: 'rabbit' },
  { hiragana: 'さる', romaji: 'saru', english: 'monkey' },
  { hiragana: 'くま', romaji: 'kuma', english: 'bear' },
  { hiragana: 'きつね', romaji: 'kitsune', english: 'fox' },
  { hiragana: 'たぬき', romaji: 'tanuki', english: 'raccoon dog' },
  { hiragana: 'しか', romaji: 'shika', english: 'deer' },
  { hiragana: 'ぞう', romaji: 'zou', english: 'elephant' },
  { hiragana: 'とら', romaji: 'tora', english: 'tiger' },
  { hiragana: 'かめ', romaji: 'kame', english: 'turtle' },
  { hiragana: 'へび', romaji: 'hebi', english: 'snake' },
  { hiragana: 'かえる', romaji: 'kaeru', english: 'frog' },
  { hiragana: 'むし', romaji: 'mushi', english: 'insect' },
  { hiragana: 'ちょう', romaji: 'chou', english: 'butterfly' },
  { hiragana: 'とんぼ', romaji: 'tonbo', english: 'dragonfly' },
  { hiragana: 'あり', romaji: 'ari', english: 'ant' },
  { hiragana: 'くじら', romaji: 'kujira', english: 'whale' },
  { hiragana: 'いるか', romaji: 'iruka', english: 'dolphin' },
  { hiragana: 'たこ', romaji: 'tako', english: 'octopus' },
  { hiragana: 'いか', romaji: 'ika', english: 'squid' },
  { hiragana: 'かに', romaji: 'kani', english: 'crab' },
  { hiragana: 'えび', romaji: 'ebi', english: 'shrimp' },
  { hiragana: 'とかげ', romaji: 'tokage', english: 'lizard' },
  { hiragana: 'わに', romaji: 'wani', english: 'crocodile' },
  { hiragana: 'こうもり', romaji: 'koumori', english: 'bat' },
  { hiragana: 'りす', romaji: 'risu', english: 'squirrel' },
  { hiragana: 'しまうま', romaji: 'shimauma', english: 'zebra' },
  { hiragana: 'きりん', romaji: 'kirin', english: 'giraffe' },
  { hiragana: 'らくだ', romaji: 'rakuda', english: 'camel' },
  { hiragana: 'おおかみ', romaji: 'ookami', english: 'wolf' },
  { hiragana: 'ふくろう', romaji: 'fukurou', english: 'owl' },
  { hiragana: 'はと', romaji: 'hato', english: 'pigeon' },
  { hiragana: 'すずめ', romaji: 'suzume', english: 'sparrow' },
  { hiragana: 'からす', romaji: 'karasu', english: 'crow' },
  { hiragana: 'わし', romaji: 'washi', english: 'eagle' },
  { hiragana: 'にわとり', romaji: 'niwatori', english: 'chicken' },
  { hiragana: 'あひる', romaji: 'ahiru', english: 'duck' },
  { hiragana: 'かたつむり', romaji: 'katatsumuri', english: 'snail' },
  { hiragana: 'ごはん', romaji: 'gohan', english: 'rice' },
  { hiragana: 'みず', romaji: 'mizu', english: 'water' },
  { hiragana: 'おちゃ', romaji: 'ocha', english: 'tea' },
  { hiragana: 'ぎゅうにゅう', romaji: 'gyuunyuu', english: 'milk' },
  { hiragana: 'さけ', romaji: 'sake', english: 'alcohol' },
  { hiragana: 'たまご', romaji: 'tamago', english: 'egg' },
  { hiragana: 'にく', romaji: 'niku', english: 'meat' },
  { hiragana: 'やさい', romaji: 'yasai', english: 'vegetable' },
  { hiragana: 'くだもの', romaji: 'kudamono', english: 'fruit' },
  { hiragana: 'りんご', romaji: 'ringo', english: 'apple' },
  { hiragana: 'みかん', romaji: 'mikan', english: 'mandarin orange' },
  { hiragana: 'ぶどう', romaji: 'budou', english: 'grape' },
  { hiragana: 'いちご', romaji: 'ichigo', english: 'strawberry' },
  { hiragana: 'もも', romaji: 'momo', english: 'peach' },
  { hiragana: 'なし', romaji: 'nashi', english: 'pear' },
  { hiragana: 'すいか', romaji: 'suika', english: 'watermelon' },
  { hiragana: 'かき', romaji: 'kaki', english: 'persimmon' },
  { hiragana: 'にんじん', romaji: 'ninjin', english: 'carrot' },
  { hiragana: 'じゃがいも', romaji: 'jagaimo', english: 'potato' },
  { hiragana: 'たまねぎ', romaji: 'tamanegi', english: 'onion' },
  { hiragana: 'きゅうり', romaji: 'kyuuri', english: 'cucumber' },
  { hiragana: 'なす', romaji: 'nasu', english: 'eggplant' },
  { hiragana: 'だいこん', romaji: 'daikon', english: 'radish' },
  { hiragana: 'とうふ', romaji: 'toufu', english: 'tofu' },
  { hiragana: 'みそ', romaji: 'miso', english: 'miso' },
  { hiragana: 'しょうゆ', romaji: 'shouyu', english: 'soy sauce' },
  { hiragana: 'さとう', romaji: 'satou', english: 'sugar' },
  { hiragana: 'しお', romaji: 'shio', english: 'salt' },
  { hiragana: 'あぶら', romaji: 'abura', english: 'oil' },
  { hiragana: 'めん', romaji: 'men', english: 'noodles' },
  { hiragana: 'そば', romaji: 'soba', english: 'soba noodles' },
  { hiragana: 'うどん', romaji: 'udon', english: 'udon noodles' },
  { hiragana: 'すし', romaji: 'sushi', english: 'sushi' },
  { hiragana: 'てんぷら', romaji: 'tenpura', english: 'tempura' },
  { hiragana: 'みそしる', romaji: 'misoshiru', english: 'miso soup' },
  { hiragana: 'おかし', romaji: 'okashi', english: 'sweets' },
  { hiragana: 'あめ', romaji: 'ame', english: 'candy' },
  { hiragana: 'わがし', romaji: 'wagashi', english: 'Japanese sweets' },
  { hiragana: 'ぎゅうにく', romaji: 'gyuuniku', english: 'beef' },
  { hiragana: 'ぶたにく', romaji: 'butaniku', english: 'pork' },
  { hiragana: 'とりにく', romaji: 'toriniku', english: 'chicken meat' },
  { hiragana: 'まぐろ', romaji: 'maguro', english: 'tuna' },
  { hiragana: 'さば', romaji: 'saba', english: 'mackerel' },
  { hiragana: 'のみもの', romaji: 'nomimono', english: 'drink' },
  { hiragana: 'たべもの', romaji: 'tabemono', english: 'food' },
  { hiragana: 'あさごはん', romaji: 'asagohan', english: 'breakfast' },
  { hiragana: 'ひるごはん', romaji: 'hirugohan', english: 'lunch' },
  { hiragana: 'ばんごはん', romaji: 'bangohan', english: 'dinner' },
  { hiragana: 'おべんとう', romaji: 'obentou', english: 'boxed lunch' },
  { hiragana: 'なっとう', romaji: 'nattou', english: 'fermented soybeans' },
  { hiragana: 'くり', romaji: 'kuri', english: 'chestnut' },
  { hiragana: 'れもん', romaji: 'remon', english: 'lemon' },
  { hiragana: 'さくらんぼ', romaji: 'sakuranbo', english: 'cherry' },
  { hiragana: 'やま', romaji: 'yama', english: 'mountain' },
  { hiragana: 'かわ', romaji: 'kawa', english: 'river' },
  { hiragana: 'うみ', romaji: 'umi', english: 'sea' },
  { hiragana: 'そら', romaji: 'sora', english: 'sky' },
  { hiragana: 'ほし', romaji: 'hoshi', english: 'star' },
  { hiragana: 'たいよう', romaji: 'taiyou', english: 'sun' },
  { hiragana: 'さくら', romaji: 'sakura', english: 'cherry blossom' },
  { hiragana: 'き', romaji: 'ki', english: 'tree' },
  { hiragana: 'くさ', romaji: 'kusa', english: 'grass' },
  { hiragana: 'はっぱ', romaji: 'happa', english: 'leaf' },
  { hiragana: 'いし', romaji: 'ishi', english: 'stone' },
  { hiragana: 'すな', romaji: 'suna', english: 'sand' },
  { hiragana: 'みずうみ', romaji: 'mizuumi', english: 'lake' },
  { hiragana: 'もり', romaji: 'mori', english: 'forest' },
  { hiragana: 'しま', romaji: 'shima', english: 'island' },
  { hiragana: 'みち', romaji: 'michi', english: 'road' },
  { hiragana: 'いけ', romaji: 'ike', english: 'pond' },
  { hiragana: 'ゆき', romaji: 'yuki', english: 'snow' },
  { hiragana: 'かぜ', romaji: 'kaze', english: 'wind' },
  { hiragana: 'くも', romaji: 'kumo', english: 'cloud' },
  { hiragana: 'てんき', romaji: 'tenki', english: 'weather' },
  { hiragana: 'はれ', romaji: 'hare', english: 'sunny' },
  { hiragana: 'くもり', romaji: 'kumori', english: 'cloudy' },
  { hiragana: 'かみなり', romaji: 'kaminari', english: 'thunder' },
  { hiragana: 'にじ', romaji: 'niji', english: 'rainbow' },
  { hiragana: 'きり', romaji: 'kiri', english: 'fog' },
  { hiragana: 'はる', romaji: 'haru', english: 'spring' },
  { hiragana: 'なつ', romaji: 'natsu', english: 'summer' },
  { hiragana: 'あき', romaji: 'aki', english: 'autumn' },
  { hiragana: 'ふゆ', romaji: 'fuyu', english: 'winter' },
  { hiragana: 'いえ', romaji: 'ie', english: 'house' },
  { hiragana: 'へや', romaji: 'heya', english: 'room' },
  { hiragana: 'まど', romaji: 'mado', english: 'window' },
  { hiragana: 'とびら', romaji: 'tobira', english: 'door' },
  { hiragana: 'いす', romaji: 'isu', english: 'chair' },
  { hiragana: 'つくえ', romaji: 'tsukue', english: 'desk' },
  { hiragana: 'ほん', romaji: 'hon', english: 'book' },
  { hiragana: 'えんぴつ', romaji: 'enpitsu', english: 'pencil' },
  { hiragana: 'かばん', romaji: 'kaban', english: 'bag' },
  { hiragana: 'とけい', romaji: 'tokei', english: 'clock' },
  { hiragana: 'でんわ', romaji: 'denwa', english: 'telephone' },
  { hiragana: 'かがみ', romaji: 'kagami', english: 'mirror' },
  { hiragana: 'さら', romaji: 'sara', english: 'plate' },
  { hiragana: 'ちゃわん', romaji: 'chawan', english: 'tea cup' },
  { hiragana: 'はし', romaji: 'hashi', english: 'chopsticks' },
  { hiragana: 'なべ', romaji: 'nabe', english: 'pot' },
  { hiragana: 'ふとん', romaji: 'futon', english: 'futon' },
  { hiragana: 'まくら', romaji: 'makura', english: 'pillow' },
  { hiragana: 'たな', romaji: 'tana', english: 'shelf' },
  { hiragana: 'かぎ', romaji: 'kagi', english: 'key' },
  { hiragana: 'でんき', romaji: 'denki', english: 'electricity' },
  { hiragana: 'ふろ', romaji: 'furo', english: 'bath' },
  { hiragana: 'おてあらい', romaji: 'otearai', english: 'restroom' },
  { hiragana: 'だいどころ', romaji: 'daidokoro', english: 'kitchen' },
  { hiragana: 'にわ', romaji: 'niwa', english: 'garden' },
  { hiragana: 'やね', romaji: 'yane', english: 'roof' },
  { hiragana: 'かべ', romaji: 'kabe', english: 'wall' },
  { hiragana: 'ゆか', romaji: 'yuka', english: 'floor' },
  { hiragana: 'ごみ', romaji: 'gomi', english: 'trash' },
  { hiragana: 'しんぶん', romaji: 'shinbun', english: 'newspaper' },
  { hiragana: 'ざっし', romaji: 'zasshi', english: 'magazine' },
  { hiragana: 'てがみ', romaji: 'tegami', english: 'letter' },
  { hiragana: 'きって', romaji: 'kitte', english: 'stamp' },
  { hiragana: 'ふく', romaji: 'fuku', english: 'clothes' },
  { hiragana: 'ぼうし', romaji: 'boushi', english: 'hat' },
  { hiragana: 'くつ', romaji: 'kutsu', english: 'shoes' },
  { hiragana: 'くつした', romaji: 'kutsushita', english: 'socks' },
  { hiragana: 'てぶくろ', romaji: 'tebukuro', english: 'gloves' },
  { hiragana: 'めがね', romaji: 'megane', english: 'glasses' },
  { hiragana: 'ゆびわ', romaji: 'yubiwa', english: 'ring' },
  { hiragana: 'きもの', romaji: 'kimono', english: 'kimono' },
  { hiragana: 'したぎ', romaji: 'shitagi', english: 'underwear' },
  { hiragana: 'がっこう', romaji: 'gakkou', english: 'school' },
  { hiragana: 'せんせい', romaji: 'sensei', english: 'teacher' },
  { hiragana: 'がくせい', romaji: 'gakusei', english: 'student' },
  { hiragana: 'きょうしつ', romaji: 'kyoushitsu', english: 'classroom' },
  { hiragana: 'としょかん', romaji: 'toshokan', english: 'library' },
  { hiragana: 'びょういん', romaji: 'byouin', english: 'hospital' },
  { hiragana: 'いしゃ', romaji: 'isha', english: 'doctor' },
  { hiragana: 'かいしゃ', romaji: 'kaisha', english: 'company' },
  { hiragana: 'しごと', romaji: 'shigoto', english: 'work' },
  { hiragana: 'べんきょう', romaji: 'benkyou', english: 'study' },
  { hiragana: 'しゅくだい', romaji: 'shukudai', english: 'homework' },
  { hiragana: 'しけん', romaji: 'shiken', english: 'exam' },
  { hiragana: 'じゅぎょう', romaji: 'jugyou', english: 'lesson' },
  { hiragana: 'きょうかしょ', romaji: 'kyoukasho', english: 'textbook' },
  { hiragana: 'こうえん', romaji: 'kouen', english: 'park' },
  { hiragana: 'えき', romaji: 'eki', english: 'station' },
  { hiragana: 'みせ', romaji: 'mise', english: 'shop' },
  { hiragana: 'ぎんこう', romaji: 'ginkou', english: 'bank' },
  { hiragana: 'ゆうびんきょく', romaji: 'yuubinkyoku', english: 'post office' },
  { hiragana: 'こうばん', romaji: 'kouban', english: 'police box' },
  { hiragana: 'たべる', romaji: 'taberu', english: 'to eat' },
  { hiragana: 'のむ', romaji: 'nomu', english: 'to drink' },
  { hiragana: 'みる', romaji: 'miru', english: 'to see' },
  { hiragana: 'きく', romaji: 'kiku', english: 'to listen' },
  { hiragana: 'はなす', romaji: 'hanasu', english: 'to speak' },
  { hiragana: 'よむ', romaji: 'yomu', english: 'to read' },
  { hiragana: 'かく', romaji: 'kaku', english: 'to write' },
  { hiragana: 'いく', romaji: 'iku', english: 'to go' },
  { hiragana: 'くる', romaji: 'kuru', english: 'to come' },
  { hiragana: 'ねる', romaji: 'neru', english: 'to sleep' },
  { hiragana: 'おきる', romaji: 'okiru', english: 'to wake up' },
  { hiragana: 'はたらく', romaji: 'hataraku', english: 'to work' },
  { hiragana: 'やすむ', romaji: 'yasumu', english: 'to rest' },
  { hiragana: 'あそぶ', romaji: 'asobu', english: 'to play' },
  { hiragana: 'べんきょうする', romaji: 'benkyousuru', english: 'to study' },
  { hiragana: 'かう', romaji: 'kau', english: 'to buy' },
  { hiragana: 'うる', romaji: 'uru', english: 'to sell' },
  { hiragana: 'つくる', romaji: 'tsukuru', english: 'to make' },
  { hiragana: 'もつ', romaji: 'motsu', english: 'to hold' },
  { hiragana: 'すわる', romaji: 'suwaru', english: 'to sit' },
  { hiragana: 'たつ', romaji: 'tatsu', english: 'to stand' },
  { hiragana: 'あるく', romaji: 'aruku', english: 'to walk' },
  { hiragana: 'はしる', romaji: 'hashiru', english: 'to run' },
  { hiragana: 'およぐ', romaji: 'oyogu', english: 'to swim' },
  { hiragana: 'とぶ', romaji: 'tobu', english: 'to fly' },
  { hiragana: 'わらう', romaji: 'warau', english: 'to laugh' },
  { hiragana: 'なく', romaji: 'naku', english: 'to cry' },
  { hiragana: 'おこる', romaji: 'okoru', english: 'to get angry' },
  { hiragana: 'よろこぶ', romaji: 'yorokobu', english: 'to be glad' },
  { hiragana: 'おもう', romaji: 'omou', english: 'to think' },
  { hiragana: 'しる', romaji: 'shiru', english: 'to know' },
  { hiragana: 'わすれる', romaji: 'wasureru', english: 'to forget' },
  { hiragana: 'おぼえる', romaji: 'oboeru', english: 'to remember' },
  { hiragana: 'おしえる', romaji: 'oshieru', english: 'to teach' },
  { hiragana: 'ならう', romaji: 'narau', english: 'to learn' },
  { hiragana: 'てつだう', romaji: 'tetsudau', english: 'to help' },
  { hiragana: 'まつ', romaji: 'matsu', english: 'to wait' },
  { hiragana: 'あける', romaji: 'akeru', english: 'to open' },
  { hiragana: 'しめる', romaji: 'shimeru', english: 'to close' },
  { hiragana: 'はいる', romaji: 'hairu', english: 'to enter' },
  { hiragana: 'でる', romaji: 'deru', english: 'to exit' },
  { hiragana: 'おす', romaji: 'osu', english: 'to push' },
  { hiragana: 'ひく', romaji: 'hiku', english: 'to pull' },
  { hiragana: 'つかう', romaji: 'tsukau', english: 'to use' },
  { hiragana: 'あらう', romaji: 'arau', english: 'to wash' },
  { hiragana: 'きる', romaji: 'kiru', english: 'to cut' },
  { hiragana: 'はく', romaji: 'haku', english: 'to put on (pants/shoes)' },
  { hiragana: 'ぬぐ', romaji: 'nugu', english: 'to take off' },
  { hiragana: 'おわる', romaji: 'owaru', english: 'to finish' },
  { hiragana: 'はじまる', romaji: 'hajimaru', english: 'to begin' },
  { hiragana: 'きえる', romaji: 'kieru', english: 'to disappear' },
  { hiragana: 'うたう', romaji: 'utau', english: 'to sing' },
  { hiragana: 'おどる', romaji: 'odoru', english: 'to dance' },
  { hiragana: 'まがる', romaji: 'magaru', english: 'to turn' },
  { hiragana: 'わたる', romaji: 'wataru', english: 'to cross' },
  { hiragana: 'とまる', romaji: 'tomaru', english: 'to stop' },
  { hiragana: 'うごく', romaji: 'ugoku', english: 'to move' },
  { hiragana: 'さわる', romaji: 'sawaru', english: 'to touch' },
  { hiragana: 'かりる', romaji: 'kariru', english: 'to borrow' },
  { hiragana: 'かす', romaji: 'kasu', english: 'to lend' },
  { hiragana: 'かえす', romaji: 'kaesu', english: 'to return (something)' },
  { hiragana: 'さがす', romaji: 'sagasu', english: 'to search' },
  { hiragana: 'みつける', romaji: 'mitsukeru', english: 'to find' },
  { hiragana: 'おおきい', romaji: 'ookii', english: 'big' },
  { hiragana: 'ちいさい', romaji: 'chiisai', english: 'small' },
  { hiragana: 'たかい', romaji: 'takai', english: 'expensive/tall' },
  { hiragana: 'やすい', romaji: 'yasui', english: 'cheap' },
  { hiragana: 'ひくい', romaji: 'hikui', english: 'low' },
  { hiragana: 'ながい', romaji: 'nagai', english: 'long' },
  { hiragana: 'みじかい', romaji: 'mijikai', english: 'short' },
  { hiragana: 'あたらしい', romaji: 'atarashii', english: 'new' },
  { hiragana: 'ふるい', romaji: 'furui', english: 'old (thing)' },
  { hiragana: 'あつい', romaji: 'atsui', english: 'hot' },
  { hiragana: 'さむい', romaji: 'samui', english: 'cold (weather)' },
  { hiragana: 'つめたい', romaji: 'tsumetai', english: 'cold (touch)' },
  { hiragana: 'あたたかい', romaji: 'atatakai', english: 'warm' },
  { hiragana: 'すずしい', romaji: 'suzushii', english: 'cool' },
  { hiragana: 'おもい', romaji: 'omoi', english: 'heavy' },
  { hiragana: 'かるい', romaji: 'karui', english: 'light (weight)' },
  { hiragana: 'はやい', romaji: 'hayai', english: 'fast' },
  { hiragana: 'おそい', romaji: 'osoi', english: 'slow' },
  { hiragana: 'むずかしい', romaji: 'muzukashii', english: 'difficult' },
  { hiragana: 'やさしい', romaji: 'yasashii', english: 'easy/kind' },
  { hiragana: 'おいしい', romaji: 'oishii', english: 'delicious' },
  { hiragana: 'まずい', romaji: 'mazui', english: 'bad tasting' },
  { hiragana: 'たのしい', romaji: 'tanoshii', english: 'fun' },
  { hiragana: 'うれしい', romaji: 'ureshii', english: 'happy' },
  { hiragana: 'かなしい', romaji: 'kanashii', english: 'sad' },
  { hiragana: 'こわい', romaji: 'kowai', english: 'scary' },
  { hiragana: 'いそがしい', romaji: 'isogashii', english: 'busy' },
  { hiragana: 'ひろい', romaji: 'hiroi', english: 'spacious' },
  { hiragana: 'せまい', romaji: 'semai', english: 'narrow' },
  { hiragana: 'きれい', romaji: 'kirei', english: 'pretty' },
  { hiragana: 'きたない', romaji: 'kitanai', english: 'dirty' },
  { hiragana: 'げんきな', romaji: 'genkina', english: 'energetic' },
  { hiragana: 'しずかな', romaji: 'shizukana', english: 'quiet' },
  { hiragana: 'にぎやかな', romaji: 'nigiyakana', english: 'lively' },
  { hiragana: 'べんりな', romaji: 'benrina', english: 'convenient' },
  { hiragana: 'ゆうめいな', romaji: 'yuumeina', english: 'famous' },
  { hiragana: 'だいすきな', romaji: 'daisukina', english: 'favorite' },
  { hiragana: 'きらいな', romaji: 'kiraina', english: 'disliked' },
  { hiragana: 'じょうずな', romaji: 'jouzuna', english: 'skillful' },
  { hiragana: 'へたな', romaji: 'hetana', english: 'unskillful' },
  { hiragana: 'しんせつな', romaji: 'shinsetsuna', english: 'kind' },
  { hiragana: 'まじめな', romaji: 'majimena', english: 'serious' },
  { hiragana: 'だれ', romaji: 'dare', english: 'who' },
  { hiragana: 'なに', romaji: 'nani', english: 'what' },
  { hiragana: 'どこ', romaji: 'doko', english: 'where' },
  { hiragana: 'いつ', romaji: 'itsu', english: 'when' },
  { hiragana: 'どうして', romaji: 'doushite', english: 'why' },
  { hiragana: 'どう', romaji: 'dou', english: 'how' },
  { hiragana: 'どちら', romaji: 'dochira', english: 'which way' },
  { hiragana: 'どれ', romaji: 'dore', english: 'which' },
  { hiragana: 'いくら', romaji: 'ikura', english: 'how much' },
  { hiragana: 'いくつ', romaji: 'ikutsu', english: 'how many' },
  { hiragana: 'たのしみ', romaji: 'tanoshimi', english: 'looking forward' },
  { hiragana: 'しんぱい', romaji: 'shinpai', english: 'worry' },
  { hiragana: 'あんしん', romaji: 'anshin', english: 'relief' },
  { hiragana: 'びっくり', romaji: 'bikkuri', english: 'surprise' },
  { hiragana: 'こまる', romaji: 'komaru', english: 'to be troubled' },
  { hiragana: 'つかれる', romaji: 'tsukareru', english: 'to get tired' },
  { hiragana: 'ねむい', romaji: 'nemui', english: 'sleepy' },
  { hiragana: 'おなかがすく', romaji: 'onakagasuku', english: 'to get hungry' },
  { hiragana: 'のどがかわく', romaji: 'nodogakawaku', english: 'to get thirsty' },
  { hiragana: 'さびしい', romaji: 'sabishii', english: 'lonely' },
  { hiragana: 'はずかしい', romaji: 'hazukashii', english: 'embarrassed' },
  { hiragana: 'くやしい', romaji: 'kuyashii', english: 'frustrated' },
  { hiragana: 'くるま', romaji: 'kuruma', english: 'car' },
  { hiragana: 'でんしゃ', romaji: 'densha', english: 'train' },
  { hiragana: 'じてんしゃ', romaji: 'jitensha', english: 'bicycle' },
  { hiragana: 'ひこうき', romaji: 'hikouki', english: 'airplane' },
  { hiragana: 'ふね', romaji: 'fune', english: 'ship' },
  { hiragana: 'ちかてつ', romaji: 'chikatetsu', english: 'subway' },
  { hiragana: 'どうろ', romaji: 'douro', english: 'road' },
  { hiragana: 'くうこう', romaji: 'kuukou', english: 'airport' },
  { hiragana: 'かんごし', romaji: 'kangoshi', english: 'nurse' },
  { hiragana: 'けいさつかん', romaji: 'keisatsukan', english: 'police officer' },
  { hiragana: 'しょうぼうし', romaji: 'shouboushi', english: 'firefighter' },
  { hiragana: 'きょうし', romaji: 'kyoushi', english: 'teacher' },
  { hiragana: 'いんしょくてん', romaji: 'inshokuten', english: 'restaurant worker' },
  { hiragana: 'のうか', romaji: 'nouka', english: 'farmer' },
  { hiragana: 'うんてんしゅ', romaji: 'untenshu', english: 'driver' },
  { hiragana: 'かしゅ', romaji: 'kashu', english: 'singer' },
  { hiragana: 'がか', romaji: 'gaka', english: 'painter' },
  { hiragana: 'さっか', romaji: 'sakka', english: 'writer' },
  { hiragana: 'いちば', romaji: 'ichiba', english: 'market' },
  { hiragana: 'やおや', romaji: 'yaoya', english: 'greengrocer' },
  { hiragana: 'ぱんや', romaji: 'pan\'ya', english: 'bakery' },
  { hiragana: 'にくや', romaji: 'nikuya', english: 'butcher shop' },
  { hiragana: 'ほんや', romaji: 'hon\'ya', english: 'bookstore' },
  { hiragana: 'せかい', romaji: 'sekai', english: 'world' },
  { hiragana: 'くに', romaji: 'kuni', english: 'country' },
  { hiragana: 'まち', romaji: 'machi', english: 'town' },
  { hiragana: 'むら', romaji: 'mura', english: 'village' },
  { hiragana: 'とかい', romaji: 'tokai', english: 'city' },
  { hiragana: 'いなか', romaji: 'inaka', english: 'countryside' },
  { hiragana: 'ちず', romaji: 'chizu', english: 'map' },
  { hiragana: 'きた', romaji: 'kita', english: 'north' },
  { hiragana: 'みなみ', romaji: 'minami', english: 'south' },
  { hiragana: 'ひがし', romaji: 'higashi', english: 'east' },
  { hiragana: 'にし', romaji: 'nishi', english: 'west' },
  { hiragana: 'みぎ', romaji: 'migi', english: 'right' },
  { hiragana: 'ひだり', romaji: 'hidari', english: 'left' },
  { hiragana: 'うえ', romaji: 'ue', english: 'above' },
  { hiragana: 'した', romaji: 'shita', english: 'below' },
  { hiragana: 'まえ', romaji: 'mae', english: 'front' },
  { hiragana: 'うしろ', romaji: 'ushiro', english: 'behind' },
  { hiragana: 'なか', romaji: 'naka', english: 'inside' },
  { hiragana: 'そと', romaji: 'soto', english: 'outside' },
  { hiragana: 'ちかく', romaji: 'chikaku', english: 'nearby' },
  { hiragana: 'とおい', romaji: 'tooi', english: 'far' },
]
