// Bedroom (SPEC.md section 6): the Calico's precision work. Trinkets,
// perfume, the ceiling fan, and a sleeping human who must NOT be sat on.
import type { LevelDef } from './types'
import { FY, PERCH, obj, precious, shelfWith, stack } from './prefabs'

const NIGHT_TOP = FY - 120

export const BEDROOM: LevelDef[] = [
  {
    id: 'bedroom-1',
    room: 'bedroom',
    index: 1,
    title: 'Trinket Shelf',
    width: 1800,
    height: 1000,
    perch: PERCH,
    lineup: ['calico', 'calico', 'calico'],
    stars: [0, 7750, 11000],
    coach: ['The Calico SWATS: tap up to 3 times mid-air to slap small things off shelves.'],
    objects: [
      ...shelfWith(1250, 600, 320, [precious('figurine'), 'candle', precious('figurine'), 'candle', precious('figurine')]),
      obj('nightstand', 1300, FY),
      obj('candle', 1280, NIGHT_TOP),
    ],
  },
  {
    id: 'bedroom-2',
    room: 'bedroom',
    index: 2,
    title: 'Perfume Row',
    width: 1900,
    height: 1000,
    perch: PERCH,
    lineup: ['calico', 'siamese', 'calico'],
    stars: [0, 5250, 7500],
    objects: [
      obj('nightstand', 1000, FY),
      obj('perfume', 970, NIGHT_TOP, { precious: true }),
      obj('perfume', 1030, NIGHT_TOP),
      obj('table', 1500, FY),
      obj('perfume', 1430, FY - 150),
      obj('perfume', 1470, FY - 150, { precious: true }),
      obj('perfume', 1510, FY - 150),
      obj('snowGlobe', 1570, FY - 150, { precious: true }),
    ],
  },
  {
    id: 'bedroom-3',
    room: 'bedroom',
    index: 3,
    title: 'Fan Flinger',
    width: 2200,
    height: 1000,
    perch: PERCH,
    lineup: ['calico', 'tabby', 'calico'],
    stars: [0, 5000, 7250],
    coach: ['Fly into the ceiling fan to get flung. Wheee!'],
    objects: [
      obj('fan', 900, 490),
      ...shelfWith(1900, 320, 220, [precious('vase'), 'candle', precious('figurine')]),
      obj('nightstand', 1900, FY),
      obj('lamp', 1900, NIGHT_TOP),
      obj('laundryPile', 1300, FY),
    ],
  },
  {
    id: 'bedroom-4',
    room: 'bedroom',
    index: 4,
    title: 'Tiptoe',
    width: 1900,
    height: 1000,
    perch: PERCH,
    lineup: ['calico', 'calico', 'tabby'],
    stars: [0, 9250, 13250],
    coach: ['The bed is bouncy. Just… don’t land on the human’s face.'],
    objects: [
      obj('nightstand', 820, FY),
      obj('lamp', 820, NIGHT_TOP, { precious: true }),
      obj('bed', 1150, FY),
      obj('humanFace', 1000, FY - 110),
      obj('nightstand', 1480, FY),
      obj('vase', 1480, NIGHT_TOP, { precious: true }),
      obj('alarmClock', 1440, NIGHT_TOP),
    ],
  },
  {
    id: 'bedroom-5',
    room: 'bedroom',
    index: 5,
    title: 'The Snooze Button',
    width: 1900,
    height: 1000,
    perch: PERCH,
    lineup: ['calico', 'siamese', 'coon', 'tabby'],
    stars: [0, 12000, 17250],
    coach: ['Knock the alarm clock off the nightstand before it rings!'],
    objects: [
      obj('nightstand', 1300, FY),
      obj('alarmClock', 1325, NIGHT_TOP, { precious: true }),
      ...stack(1276, NIGHT_TOP, ['book']),
      obj('glassPane', 1253, NIGHT_TOP),
      ...shelfWith(1300, 560, 260, ['figurine', precious('snowGlobe'), 'figurine', 'candle']),
      obj('bed', 1650, FY, { w: 300 }),
      ...stack(1600, FY - 110, ['pillow', 'pillow']),
    ],
  },
]
