// Living Room (SPEC.md section 6): the Maine Coon arrives. Laundry,
// wood, floorboards, the sofa gap and the curtains.
import type { LevelDef } from './types'
import { FY, PERCH, obj, precious, shelfWith, stack } from './prefabs'

export const LIVING: LevelDef[] = [
  {
    id: 'living-1',
    room: 'living',
    index: 1,
    title: 'Laundry Mountain',
    width: 1900,
    height: 1000,
    perch: PERCH,
    lineup: ['coon', 'coon', 'tabby'],
    stars: [0, 9500, 13750],
    coach: ['Meet the Maine Coon: heavy and slow. HOLD mid-air to go full LOAF for extra smash.'],
    objects: [
      ...stack(1150, FY, ['laundryBasket', 'laundryBasket', 'laundryBasket', precious('vase')]),
      obj('laundryPile', 1020, FY),
      ...stack(1450, FY, ['laundryBasket', 'laundryBasket', 'pillow', precious('jar')]),
      obj('laundryPile', 1600, FY),
    ],
  },
  {
    id: 'living-2',
    room: 'living',
    index: 2,
    title: 'Under the Sofa',
    width: 1800,
    height: 1000,
    perch: PERCH,
    lineup: ['tabby', 'tabby', 'coon'],
    stars: [0, 5500, 7750],
    coach: ['Cats are liquid. A low, flat pounce pours right under the sofa.'],
    objects: [
      obj('sofa', 1100, FY),
      obj('plate', 1110, FY, { precious: true }),
      obj('vase', 1100, FY - 120 + 0, { precious: true }),
      obj('pillow', 1010, FY - 40 - 50),
      obj('pillow', 1190, FY - 40 - 50),
      obj('lamp', 1400, FY),
    ],
  },
  {
    id: 'living-3',
    room: 'living',
    index: 3,
    title: 'Creaky Boards',
    width: 1800,
    height: 1000,
    perch: PERCH,
    lineup: ['coon', 'coon', 'coon'],
    stars: [0, 12250, 17500],
    coach: ['TAP mid-air to CHONK SLAM straight down. Only a Maine Coon breaks floorboards.'],
    objects: [
      obj('block', 900, FY, { w: 40, h: 160 }),
      obj('block', 1340, FY, { w: 40, h: 160 }),
      obj('floorboard', 970, FY - 160, { w: 100 }),
      obj('floorboard', 1070, FY - 160, { w: 100 }),
      obj('floorboard', 1170, FY - 160, { w: 100 }),
      obj('floorboard', 1270, FY - 160, { w: 100 }),
      obj('vase', 1120, FY, { precious: true }),
      obj('jar', 1030, FY),
      obj('crate', 1010, FY - 182),
      obj('crate', 1230, FY - 182),
    ],
  },
  {
    id: 'living-4',
    room: 'living',
    index: 4,
    title: 'Curtain Call',
    width: 1900,
    height: 1000,
    perch: PERCH,
    lineup: ['tabby', 'coon', 'tabby'],
    stars: [0, 8500, 12250],
    coach: ['Grab the curtain (HOLD while touching it) and swing up to the mantel.'],
    objects: [
      obj('curtain', 700, 700),
      obj('block', 1500, FY, { w: 260, h: 540 }),
      ...stack(1420, FY - 540, ['trophy']),
      obj('vase', 1500, FY - 540, { precious: true }),
      obj('figurine', 1580, FY - 540, { precious: true }),
      obj('laundryPile', 1150, FY),
    ],
  },
  {
    id: 'living-5',
    room: 'living',
    index: 5,
    title: 'Bookcase Domino',
    width: 2000,
    height: 1000,
    perch: PERCH,
    lineup: ['coon', 'tabby', 'coon', 'tabby'],
    stars: [0, 9000, 12750],
    objects: [
      ...shelfWith(1350, 760, 300, ['book', 'book', 'book', 'book', 'book', precious('figurine')], 'bookcase'),
      ...shelfWith(1350, 560, 300, [precious('vase'), 'book', 'book', 'book', 'book', 'book'], 'bookcase'),
      ...stack(1050, FY, ['crate', 'woodBlock', 'woodBlock']),
      obj('post', 1600, FY),
      obj('post', 1660, FY),
      obj('plank', 1630, FY - 96),
      obj('jar', 1630, FY - 112, { precious: true }),
    ],
  },
]
