// Home Office (SPEC.md section 6): the Siamese and the Dog. Thin glass,
// electronics, and a very light sleeper.
import type { LevelDef } from './types'
import { FY, PERCH, obj, precious, shelfWith, stack } from './prefabs'

const DESK_TOP = FY - 150

export const OFFICE: LevelDef[] = [
  {
    id: 'office-1',
    room: 'office',
    index: 1,
    title: 'Glass Cabinet',
    width: 1800,
    height: 1000,
    perch: PERCH,
    lineup: ['siamese', 'siamese', 'siamese'],
    stars: [0, 18750, 27000],
    coach: ['The Siamese SCREAMS: tap mid-air and thin glass inside the ring shatters.'],
    objects: [
      obj('block', 1300, FY, { w: 260, h: 200 }),
      obj('windowPane', 1178, FY - 200),
      obj('windowPane', 1422, FY - 200),
      obj('block', 1300, FY - 360, { w: 280, h: 20 }),
      obj('wineGlass', 1240, FY - 200, { precious: true }),
      obj('wineGlass', 1300, FY - 200, { precious: true }),
      obj('wineGlass', 1360, FY - 200, { precious: true }),
    ],
  },
  {
    id: 'office-2',
    room: 'office',
    index: 2,
    title: 'Monitor Tower',
    width: 1800,
    height: 1000,
    perch: PERCH,
    lineup: ['siamese', 'coon', 'tabby'],
    stars: [0, 9750, 14000],
    objects: [
      obj('desk', 1250, FY),
      ...stack(1180, DESK_TOP, ['box', 'box', precious('monitor')]),
      obj('monitor', 1340, DESK_TOP),
      obj('mug', 1400, DESK_TOP),
      obj('paperStack', 1115, DESK_TOP),
    ],
  },
  {
    id: 'office-3',
    room: 'office',
    index: 3,
    title: 'Let Sleeping Dogs Lie',
    width: 2000,
    height: 1000,
    perch: PERCH,
    lineup: ['siamese', 'siamese', 'tabby'],
    stars: [0, 10250, 14500],
    dog: { x: 820 },
    coach: ['The dog is a light sleeper. A scream (or smashing glass) nearby sends it on a rampage.'],
    objects: [
      obj('dogBed', 820, FY),
      obj('glassPane', 980, FY),
      ...stack(1500, FY, ['crate', 'crate', precious('vase')]),
      obj('post', 1380, FY),
      obj('post', 1640, FY),
      obj('jar', 1700, FY, { precious: true }),
    ],
  },
  {
    id: 'office-4',
    room: 'office',
    index: 4,
    title: 'Window Panes',
    width: 1900,
    height: 1000,
    perch: PERCH,
    lineup: ['siamese', 'tabby', 'siamese'],
    stars: [0, 11500, 16500],
    objects: [
      ...shelfWith(1420, 500, 220, [precious('jar'), 'perfume', 'spiceJar']),
      obj('windowPane', 1280, 500),
      ...shelfWith(1520, 760, 220, ['mug', precious('vase'), 'mug']),
      obj('windowPane', 1380, 760),
      obj('desk', 1600, FY),
    ],
  },
  {
    id: 'office-5',
    room: 'office',
    index: 5,
    title: 'Deadline Disaster',
    width: 2200,
    height: 1000,
    perch: PERCH,
    lineup: ['siamese', 'coon', 'tabby', 'siamese'],
    stars: [0, 9750, 14000],
    dog: { x: 1850 },
    objects: [
      obj('desk', 1250, FY),
      obj('monitor', 1235, DESK_TOP, { precious: true }),
      obj('lamp', 1375, DESK_TOP),
      ...stack(1122, DESK_TOP, ['paperStack', 'paperStack', 'mug']),
      ...shelfWith(1700, 500, 240, ['trophy', precious('vase'), 'book', 'book']),
      obj('dogBed', 1850, FY),
      obj('glassPane', 1720, FY),
      obj('jar', 2050, FY, { precious: true }),
    ],
  },
]
