// A bank of 200 multiple-choice trivia questions spanning word/etymology
// trivia (phobia names, linguistic terms), science, history, geography, arts
// & pop culture, and math/logic. Each question has exactly 4 choices, one of
// which matches `answer` exactly, with wrong choices chosen to be
// plausible same-category near-misses rather than random noise.
export interface Question {
  question: string
  choices: string[]
  answer: string
}

export const QUESTIONS: Question[] = [
  { question: 'What is the word for the fear of the number 12, which ironically has 12 letters?', choices: ['Dodecaphobia', 'Triskaidekaphobia', 'Decaphobia', 'Numerophobia'], answer: 'Dodecaphobia' },
  { question: 'The fear of palindromes is also a palindrome. What is that word?', choices: ['Aibohphobia', 'Palindromophobia', 'Symmetraphobia', 'Repetophobia'], answer: 'Aibohphobia' },
  { question: 'The inability to pronounce a soft \'G\' starts with a \'G\'. What is it?', choices: ['Gammacism', 'Lambdacism', 'Rhotacism', 'Sigmatism'], answer: 'Gammacism' },
  { question: 'What is the fear of long words called, itself a famously long word?', choices: ['Hippopotomonstrosesquippedaliophobia', 'Sesquipedalophobia', 'Logophobia', 'Verbaphobia'], answer: 'Hippopotomonstrosesquippedaliophobia' },
  { question: 'What is the fear of spiders called?', choices: ['Arachnophobia', 'Entomophobia', 'Myrmecophobia', 'Insectophobia'], answer: 'Arachnophobia' },
  { question: 'What is the fear of heights called?', choices: ['Acrophobia', 'Altophobia', 'Bathophobia', 'Vertigophobia'], answer: 'Acrophobia' },
  { question: 'What is the fear of open or crowded public spaces called?', choices: ['Agoraphobia', 'Claustrophobia', 'Enochlophobia', 'Demophobia'], answer: 'Agoraphobia' },
  { question: 'What is the fear of enclosed spaces called?', choices: ['Claustrophobia', 'Agoraphobia', 'Cleithrophobia', 'Taphophobia'], answer: 'Claustrophobia' },
  { question: 'What is the fear of the number 13 called?', choices: ['Triskaidekaphobia', 'Dodecaphobia', 'Numerophobia', 'Tetraphobia'], answer: 'Triskaidekaphobia' },
  { question: 'What is the fear of clowns called?', choices: ['Coulrophobia', 'Pediophobia', 'Automatonophobia', 'Masklophobia'], answer: 'Coulrophobia' },
  { question: 'What is the fear of thunder and lightning called?', choices: ['Astraphobia', 'Ombrophobia', 'Nyctophobia', 'Anemophobia'], answer: 'Astraphobia' },
  { question: 'What is the fear of water called?', choices: ['Aquaphobia', 'Hydrophobia', 'Thalassophobia', 'Potamophobia'], answer: 'Aquaphobia' },
  { question: 'What is the fear of the dark called?', choices: ['Nyctophobia', 'Scotophobia', 'Achluophobia', 'Lygophobia'], answer: 'Nyctophobia' },
  { question: 'What is the fear of blood called?', choices: ['Hemophobia', 'Traumatophobia', 'Necrophobia', 'Algophobia'], answer: 'Hemophobia' },
  { question: 'What is the fear of flying called?', choices: ['Aviophobia', 'Acrophobia', 'Aerophobia', 'Altophobia'], answer: 'Aviophobia' },
  { question: 'What is the fear of dogs called?', choices: ['Cynophobia', 'Ailurophobia', 'Zoophobia', 'Musophobia'], answer: 'Cynophobia' },
  { question: 'What is the fear of snakes called?', choices: ['Ophidiophobia', 'Herpetophobia', 'Arachnophobia', 'Batrachophobia'], answer: 'Ophidiophobia' },
  { question: 'What is the fear of germs called?', choices: ['Mysophobia', 'Verminophobia', 'Bacillophobia', 'Molysmophobia'], answer: 'Mysophobia' },
  { question: 'What is the fear of death called?', choices: ['Thanatophobia', 'Necrophobia', 'Taphophobia', 'Mortiphobia'], answer: 'Thanatophobia' },
  { question: 'What is the fear of strangers or foreigners called?', choices: ['Xenophobia', 'Agoraphobia', 'Anthropophobia', 'Sociophobia'], answer: 'Xenophobia' },
  { question: 'What do you call a word that reads the same backwards and forwards?', choices: ['Palindrome', 'Anagram', 'Acronym', 'Homograph'], answer: 'Palindrome' },
  { question: 'What do you call a word or phrase formed by rearranging the letters of another?', choices: ['Anagram', 'Palindrome', 'Pangram', 'Portmanteau'], answer: 'Anagram' },
  { question: 'What is the term for words that sound the same but differ in meaning or spelling?', choices: ['Homophones', 'Homographs', 'Heteronyms', 'Synonyms'], answer: 'Homophones' },
  { question: 'What is a word spelled the same but pronounced differently depending on meaning called?', choices: ['Heteronym', 'Homophone', 'Homonym', 'Synonym'], answer: 'Heteronym' },
  { question: 'What is a word that imitates the sound it represents called?', choices: ['Onomatopoeia', 'Alliteration', 'Assonance', 'Consonance'], answer: 'Onomatopoeia' },
  { question: 'What figure of speech means saying the opposite of what you mean for effect?', choices: ['Irony', 'Metaphor', 'Hyperbole', 'Euphemism'], answer: 'Irony' },
  { question: 'A word that is its own opposite, like \'cleave\', is called what?', choices: ['Contronym', 'Synonym', 'Antonym', 'Homonym'], answer: 'Contronym' },
  { question: 'What do you call a sentence that uses every letter of the alphabet at least once?', choices: ['Pangram', 'Palindrome', 'Anagram', 'Acrostic'], answer: 'Pangram' },
  { question: 'What do you call a word that means the same as another word?', choices: ['Synonym', 'Antonym', 'Homonym', 'Acronym'], answer: 'Synonym' },
  { question: 'What do you call a word that means the opposite of another word?', choices: ['Antonym', 'Synonym', 'Homonym', 'Contronym'], answer: 'Antonym' },
  { question: 'What is the study of the origin and history of words called?', choices: ['Etymology', 'Entomology', 'Philology', 'Linguistics'], answer: 'Etymology' },
  { question: 'What do you call a newly coined word or expression?', choices: ['Neologism', 'Archaism', 'Colloquialism', 'Idiom'], answer: 'Neologism' },
  { question: 'What is the linguistic term for shortening a word, like \'photo\' from \'photograph\'?', choices: ['Clipping', 'Blending', 'Compounding', 'Truncation'], answer: 'Clipping' },
  { question: 'The word \'quixotic\' comes from which literary character?', choices: ['Don Quixote', 'Don Juan', 'Sancho Panza', 'Robin Hood'], answer: 'Don Quixote' },
  { question: 'The word \'sandwich\' is said to be named after which English aristocrat?', choices: ['The Earl of Sandwich', 'The Duke of Wellington', 'The Earl of Essex', 'The Duke of York'], answer: 'The Earl of Sandwich' },
  { question: 'What do you call a word borrowed directly from another language?', choices: ['Loanword', 'Neologism', 'Cognate', 'Calque'], answer: 'Loanword' },
  { question: 'What is an overused phrase that has lost its original impact called?', choices: ['Cliché', 'Idiom', 'Aphorism', 'Euphemism'], answer: 'Cliché' },
  { question: 'What is the fear of public speaking called?', choices: ['Glossophobia', 'Laliophobia', 'Phonophobia', 'Verbophobia'], answer: 'Glossophobia' },
  { question: 'What is the fear of buttons called?', choices: ['Koumpounophobia', 'Trypophobia', 'Papyrophobia', 'Chromophobia'], answer: 'Koumpounophobia' },
  { question: 'What is the fear of mirrors called?', choices: ['Eisoptrophobia', 'Selenophobia', 'Photophobia', 'Spectrophobia'], answer: 'Eisoptrophobia' },
  { question: 'What is the chemical symbol for gold?', choices: ['Au', 'Ag', 'Gd', 'Go'], answer: 'Au' },
  { question: 'What is often called the powerhouse of the cell?', choices: ['Mitochondria', 'Nucleus', 'Ribosome', 'Golgi apparatus'], answer: 'Mitochondria' },
  { question: 'What planet is known as the Red Planet?', choices: ['Mars', 'Venus', 'Jupiter', 'Mercury'], answer: 'Mars' },
  { question: 'What gas do plants absorb from the atmosphere for photosynthesis?', choices: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'], answer: 'Carbon dioxide' },
  { question: 'Approximately how fast does light travel in a vacuum?', choices: ['300,000 kilometers per second', '150,000 kilometers per second', '1,000,000 kilometers per second', '30,000 kilometers per second'], answer: '300,000 kilometers per second' },
  { question: 'What is the hardest naturally occurring substance on Earth?', choices: ['Diamond', 'Quartz', 'Titanium', 'Granite'], answer: 'Diamond' },
  { question: 'What force keeps planets in orbit around the sun?', choices: ['Gravity', 'Magnetism', 'Friction', 'Inertia'], answer: 'Gravity' },
  { question: 'What is the smallest structural and functional unit of life?', choices: ['Cell', 'Atom', 'Molecule', 'Organ'], answer: 'Cell' },
  { question: 'How many bones are in the adult human body?', choices: ['206', '186', '226', '256'], answer: '206' },
  { question: 'What is the chemical formula for water?', choices: ['H2O', 'CO2', 'O2', 'H2O2'], answer: 'H2O' },
  { question: 'Which planet has the most known moons in our solar system?', choices: ['Saturn', 'Jupiter', 'Uranus', 'Neptune'], answer: 'Saturn' },
  { question: 'What is the scientific study of living organisms called?', choices: ['Biology', 'Geology', 'Chemistry', 'Physics'], answer: 'Biology' },
  { question: 'What is the process by which plants make food using sunlight called?', choices: ['Photosynthesis', 'Respiration', 'Transpiration', 'Fermentation'], answer: 'Photosynthesis' },
  { question: 'What element has the atomic number 1?', choices: ['Hydrogen', 'Helium', 'Oxygen', 'Lithium'], answer: 'Hydrogen' },
  { question: 'What is the largest organ in the human body?', choices: ['Skin', 'Liver', 'Lungs', 'Heart'], answer: 'Skin' },
  { question: 'Which type of blood cell primarily fights infection?', choices: ['White blood cell', 'Red blood cell', 'Platelet', 'Plasma cell'], answer: 'White blood cell' },
  { question: 'What is the boiling point of water at sea level in Celsius?', choices: ['100', '90', '120', '212'], answer: '100' },
  { question: 'What galaxy do we live in?', choices: ['Milky Way', 'Andromeda', 'Triangulum', 'Whirlpool'], answer: 'Milky Way' },
  { question: 'What is the scientific study of earthquakes called?', choices: ['Seismology', 'Volcanology', 'Geology', 'Tectonics'], answer: 'Seismology' },
  { question: 'What is the chemical symbol for sodium?', choices: ['Na', 'So', 'Sd', 'Nu'], answer: 'Na' },
  { question: 'What part of the cell contains most of its genetic material?', choices: ['Nucleus', 'Mitochondria', 'Cytoplasm', 'Ribosome'], answer: 'Nucleus' },
  { question: 'What is the closest star to Earth?', choices: ['The Sun', 'Proxima Centauri', 'Sirius', 'Alpha Centauri'], answer: 'The Sun' },
  { question: 'What is the freezing point of water in Celsius?', choices: ['0', '32', '10', '-10'], answer: '0' },
  { question: 'What is the SI unit of electrical resistance called?', choices: ['Ohm', 'Volt', 'Watt', 'Ampere'], answer: 'Ohm' },
  { question: 'What is the most abundant gas in Earth\'s atmosphere?', choices: ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Argon'], answer: 'Nitrogen' },
  { question: 'What is the chemical symbol for iron?', choices: ['Fe', 'Ir', 'In', 'Fr'], answer: 'Fe' },
  { question: 'How many chambers does the human heart have?', choices: ['4', '2', '3', '6'], answer: '4' },
  { question: 'Which layer of the atmosphere contains the ozone layer?', choices: ['Stratosphere', 'Troposphere', 'Mesosphere', 'Thermosphere'], answer: 'Stratosphere' },
  { question: 'What do you call an animal that eats both plants and meat?', choices: ['Omnivore', 'Herbivore', 'Carnivore', 'Insectivore'], answer: 'Omnivore' },
  { question: 'What do you call an animal that eats only plants?', choices: ['Herbivore', 'Carnivore', 'Omnivore', 'Scavenger'], answer: 'Herbivore' },
  { question: 'What do you call an animal that eats only meat?', choices: ['Carnivore', 'Herbivore', 'Omnivore', 'Detritivore'], answer: 'Carnivore' },
  { question: 'What organ pumps blood through the human body?', choices: ['Heart', 'Lungs', 'Liver', 'Kidneys'], answer: 'Heart' },
  { question: 'What is the largest planet in our solar system?', choices: ['Jupiter', 'Saturn', 'Neptune', 'Uranus'], answer: 'Jupiter' },
  { question: 'What is the smallest planet in our solar system?', choices: ['Mercury', 'Mars', 'Venus', 'Pluto'], answer: 'Mercury' },
  { question: 'What is the process by which liquid water becomes a gas called?', choices: ['Evaporation', 'Condensation', 'Precipitation', 'Sublimation'], answer: 'Evaporation' },
  { question: 'What is the scientific study of weather called?', choices: ['Meteorology', 'Astronomy', 'Climatology', 'Geology'], answer: 'Meteorology' },
  { question: 'What natural satellite orbits the Earth?', choices: ['The Moon', 'Titan', 'Europa', 'Phobos'], answer: 'The Moon' },
  { question: 'What pH value is considered neutral, like pure water?', choices: ['7', '0', '14', '10'], answer: '7' },
  { question: 'What vitamin does skin produce when exposed to sunlight?', choices: ['Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B12'], answer: 'Vitamin D' },
  { question: 'What is the largest mammal in the world?', choices: ['Blue whale', 'African elephant', 'Sperm whale', 'Giraffe'], answer: 'Blue whale' },
  { question: 'Who was the first President of the United States?', choices: ['George Washington', 'John Adams', 'Thomas Jefferson', 'Benjamin Franklin'], answer: 'George Washington' },
  { question: 'In what year did World War II end?', choices: ['1945', '1943', '1939', '1950'], answer: '1945' },
  { question: 'Who was the primary author of the Declaration of Independence?', choices: ['Thomas Jefferson', 'George Washington', 'John Adams', 'Benjamin Franklin'], answer: 'Thomas Jefferson' },
  { question: 'Which ancient wonder is located in Giza, Egypt?', choices: ['The Great Pyramid', 'The Hanging Gardens', 'The Colossus of Rhodes', 'The Lighthouse of Alexandria'], answer: 'The Great Pyramid' },
  { question: 'Who was the first man to walk on the Moon?', choices: ['Neil Armstrong', 'Buzz Aldrin', 'Michael Collins', 'John Glenn'], answer: 'Neil Armstrong' },
  { question: 'In what year did the Titanic sink?', choices: ['1912', '1905', '1920', '1898'], answer: '1912' },
  { question: 'Who was the British Prime Minister for most of World War II?', choices: ['Winston Churchill', 'Neville Chamberlain', 'Clement Attlee', 'Anthony Eden'], answer: 'Winston Churchill' },
  { question: 'What wall fell in 1989, symbolizing the end of the Cold War?', choices: ['The Berlin Wall', 'The Great Wall of China', 'Hadrian\'s Wall', 'The Iron Curtain'], answer: 'The Berlin Wall' },
  { question: 'Which empire was ruled by Julius Caesar?', choices: ['Roman Empire', 'Byzantine Empire', 'Greek Empire', 'Ottoman Empire'], answer: 'Roman Empire' },
  { question: 'In what year did Christopher Columbus first reach the Americas?', choices: ['1492', '1500', '1485', '1510'], answer: '1492' },
  { question: 'Who was the leader of Nazi Germany during World War II?', choices: ['Adolf Hitler', 'Heinrich Himmler', 'Joseph Goebbels', 'Hermann Göring'], answer: 'Adolf Hitler' },
  { question: 'What war was fought between the North and South United States from 1861 to 1865?', choices: ['The American Civil War', 'The Revolutionary War', 'The War of 1812', 'The Spanish-American War'], answer: 'The American Civil War' },
  { question: 'Who was Queen of England for over 70 years, the longest-reigning British monarch, until her death in 2022?', choices: ['Queen Elizabeth II', 'Queen Victoria', 'Queen Elizabeth I', 'Queen Anne'], answer: 'Queen Elizabeth II' },
  { question: 'What ancient civilization built Machu Picchu?', choices: ['The Inca', 'The Maya', 'The Aztec', 'The Olmec'], answer: 'The Inca' },
  { question: 'Which country gifted the Statue of Liberty to the United States?', choices: ['France', 'England', 'Spain', 'Italy'], answer: 'France' },
  { question: 'In what year did India gain independence from British rule?', choices: ['1947', '1935', '1950', '1942'], answer: '1947' },
  { question: 'Who was the first Emperor of Rome?', choices: ['Augustus', 'Julius Caesar', 'Nero', 'Constantine'], answer: 'Augustus' },
  { question: 'What treaty officially ended World War I?', choices: ['Treaty of Versailles', 'Treaty of Paris', 'Treaty of Ghent', 'Treaty of Vienna'], answer: 'Treaty of Versailles' },
  { question: 'Which U.S. President was assassinated in 1963?', choices: ['John F. Kennedy', 'Abraham Lincoln', 'William McKinley', 'James Garfield'], answer: 'John F. Kennedy' },
  { question: 'What ancient Egyptian writing system used pictures to represent words and sounds?', choices: ['Hieroglyphics', 'Cuneiform', 'Calligraphy', 'Runes'], answer: 'Hieroglyphics' },
  { question: 'What was the name of the ship that carried the Pilgrims to America in 1620?', choices: ['The Mayflower', 'The Santa Maria', 'The Speedwell', 'The Endeavour'], answer: 'The Mayflower' },
  { question: 'Who painted the ceiling of the Sistine Chapel?', choices: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'], answer: 'Michelangelo' },
  { question: 'In what year did the French Revolution begin?', choices: ['1789', '1776', '1804', '1799'], answer: '1789' },
  { question: 'Who was the South African leader who fought apartheid and became president in 1994?', choices: ['Nelson Mandela', 'Desmond Tutu', 'F.W. de Klerk', 'Steve Biko'], answer: 'Nelson Mandela' },
  { question: 'What was the name of the period of cultural rebirth in Europe following the Middle Ages?', choices: ['The Renaissance', 'The Enlightenment', 'The Reformation', 'The Baroque'], answer: 'The Renaissance' },
  { question: 'Which country was formerly known as Persia?', choices: ['Iran', 'Iraq', 'Turkey', 'Syria'], answer: 'Iran' },
  { question: 'What was the 19th-century U.S. belief that expansion across North America was justified and inevitable called?', choices: ['Manifest Destiny', 'The Monroe Doctrine', 'Westward Expansion Act', 'The Homestead Principle'], answer: 'Manifest Destiny' },
  { question: 'Who was the first woman to fly solo across the Atlantic Ocean?', choices: ['Amelia Earhart', 'Bessie Coleman', 'Jacqueline Cochran', 'Harriet Quimby'], answer: 'Amelia Earhart' },
  { question: 'What ancient Greek city-state is considered the birthplace of democracy?', choices: ['Athens', 'Sparta', 'Corinth', 'Thebes'], answer: 'Athens' },
  { question: 'What was the name of the German airship that caught fire in 1937 in New Jersey?', choices: ['The Hindenburg', 'The Graf Zeppelin', 'The Akron', 'The Shenandoah'], answer: 'The Hindenburg' },
  { question: 'Who is known as the \'Father of the United States Constitution\'?', choices: ['James Madison', 'Thomas Jefferson', 'Alexander Hamilton', 'John Jay'], answer: 'James Madison' },
  { question: 'In what year did construction of the Berlin Wall begin?', choices: ['1961', '1955', '1965', '1970'], answer: '1961' },
  { question: 'Which explorer\'s expedition was the first to circumnavigate the globe, though he died partway through?', choices: ['Ferdinand Magellan', 'Christopher Columbus', 'Vasco da Gama', 'James Cook'], answer: 'Ferdinand Magellan' },
  { question: 'What was the ancient trade route connecting China to the Mediterranean called?', choices: ['The Silk Road', 'The Spice Route', 'The Amber Road', 'The Incense Route'], answer: 'The Silk Road' },
  { question: 'Who led the Soviet Union during the Cuban Missile Crisis?', choices: ['Nikita Khrushchev', 'Joseph Stalin', 'Leonid Brezhnev', 'Vladimir Lenin'], answer: 'Nikita Khrushchev' },
  { question: 'What was the name of the global pandemic that occurred in 1918?', choices: ['The Spanish Flu', 'The Bubonic Plague', 'The Asian Flu', 'The Great Influenza War'], answer: 'The Spanish Flu' },
  { question: 'In what year did the Apollo 11 mission land the first humans on the Moon?', choices: ['1969', '1965', '1972', '1959'], answer: '1969' },
  { question: 'Which country was the first to grant women the right to vote nationally?', choices: ['New Zealand', 'United States', 'United Kingdom', 'Australia'], answer: 'New Zealand' },
  { question: 'Who was the last active Pharaoh of Egypt?', choices: ['Cleopatra', 'Nefertiti', 'Hatshepsut', 'Tutankhamun'], answer: 'Cleopatra' },
  { question: 'What event on December 7, 1941, brought the United States into World War II?', choices: ['The attack on Pearl Harbor', 'The Battle of Midway', 'The invasion of Normandy', 'The bombing of Hiroshima'], answer: 'The attack on Pearl Harbor' },
  { question: 'What is the capital of France?', choices: ['Paris', 'Lyon', 'Marseille', 'Nice'], answer: 'Paris' },
  { question: 'What is the largest continent by area?', choices: ['Asia', 'Africa', 'North America', 'Europe'], answer: 'Asia' },
  { question: 'What is the longest river in the world?', choices: ['The Nile', 'The Amazon', 'The Yangtze', 'The Mississippi'], answer: 'The Nile' },
  { question: 'What is the largest hot desert in the world?', choices: ['The Sahara', 'The Gobi', 'The Kalahari', 'The Mojave'], answer: 'The Sahara' },
  { question: 'What is the smallest country in the world by area?', choices: ['Vatican City', 'Monaco', 'San Marino', 'Liechtenstein'], answer: 'Vatican City' },
  { question: 'What is the tallest mountain in the world above sea level?', choices: ['Mount Everest', 'K2', 'Kangchenjunga', 'Denali'], answer: 'Mount Everest' },
  { question: 'What is the largest ocean on Earth?', choices: ['The Pacific Ocean', 'The Atlantic Ocean', 'The Indian Ocean', 'The Arctic Ocean'], answer: 'The Pacific Ocean' },
  { question: 'Which country has the largest population in the world as of recent estimates?', choices: ['India', 'China', 'United States', 'Indonesia'], answer: 'India' },
  { question: 'What is the capital of Japan?', choices: ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama'], answer: 'Tokyo' },
  { question: 'What is the smallest continent by area?', choices: ['Australia', 'Europe', 'Antarctica', 'South America'], answer: 'Australia' },
  { question: 'What European country is famously shaped like a boot?', choices: ['Italy', 'Greece', 'Spain', 'Portugal'], answer: 'Italy' },
  { question: 'What is the capital of Australia?', choices: ['Canberra', 'Sydney', 'Melbourne', 'Perth'], answer: 'Canberra' },
  { question: 'What ancient structure in China stretches thousands of miles across the country?', choices: ['The Great Wall of China', 'The Grand Canal', 'The Silk Road', 'The Forbidden City'], answer: 'The Great Wall of China' },
  { question: 'What is the largest country in the world by area?', choices: ['Russia', 'Canada', 'China', 'United States'], answer: 'Russia' },
  { question: 'What is the capital of Canada?', choices: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'], answer: 'Ottawa' },
  { question: 'What is considered the driest place on Earth?', choices: ['The Atacama Desert', 'The Sahara Desert', 'Death Valley', 'The Gobi Desert'], answer: 'The Atacama Desert' },
  { question: 'What is the largest island in the world?', choices: ['Greenland', 'Madagascar', 'Borneo', 'New Guinea'], answer: 'Greenland' },
  { question: 'What is the capital of Egypt?', choices: ['Cairo', 'Alexandria', 'Giza', 'Luxor'], answer: 'Cairo' },
  { question: 'What is the deepest known point in the world\'s oceans?', choices: ['The Mariana Trench', 'The Puerto Rico Trench', 'The Java Trench', 'The Tonga Trench'], answer: 'The Mariana Trench' },
  { question: 'What is the capital of Italy?', choices: ['Rome', 'Milan', 'Naples', 'Venice'], answer: 'Rome' },
  { question: 'What is the smallest U.S. state by land area?', choices: ['Rhode Island', 'Delaware', 'Connecticut', 'Hawaii'], answer: 'Rhode Island' },
  { question: 'What is the largest lake in the world by surface area?', choices: ['The Caspian Sea', 'Lake Superior', 'Lake Victoria', 'Lake Baikal'], answer: 'The Caspian Sea' },
  { question: 'What is the capital of Germany?', choices: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt'], answer: 'Berlin' },
  { question: 'What is the highest waterfall in the world?', choices: ['Angel Falls', 'Niagara Falls', 'Victoria Falls', 'Iguazu Falls'], answer: 'Angel Falls' },
  { question: 'What is the capital of Brazil?', choices: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'], answer: 'Brasília' },
  { question: 'What mountain range is often cited as the divide between Europe and Asia?', choices: ['The Ural Mountains', 'The Caucasus Mountains', 'The Alps', 'The Carpathians'], answer: 'The Ural Mountains' },
  { question: 'What is the capital of Russia?', choices: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Kazan'], answer: 'Moscow' },
  { question: 'What is the world\'s largest rainforest called?', choices: ['The Amazon Rainforest', 'The Congo Rainforest', 'The Daintree Rainforest', 'The Borneo Rainforest'], answer: 'The Amazon Rainforest' },
  { question: 'What is the capital of the United Kingdom?', choices: ['London', 'Manchester', 'Edinburgh', 'Birmingham'], answer: 'London' },
  { question: 'What is the southernmost continent on Earth?', choices: ['Antarctica', 'Australia', 'South America', 'Africa'], answer: 'Antarctica' },
  { question: 'Who wrote the play \'Romeo and Juliet\'?', choices: ['William Shakespeare', 'Christopher Marlowe', 'Ben Jonson', 'John Milton'], answer: 'William Shakespeare' },
  { question: 'Who painted the \'Mona Lisa\'?', choices: ['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Sandro Botticelli'], answer: 'Leonardo da Vinci' },
  { question: 'What novel is frequently cited as the best-selling novel of all time?', choices: ['A Tale of Two Cities', 'Don Quixote', 'The Lord of the Rings', 'War and Peace'], answer: 'A Tale of Two Cities' },
  { question: 'Who composed the Ninth Symphony despite being completely deaf?', choices: ['Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Franz Schubert'], answer: 'Ludwig van Beethoven' },
  { question: 'Who wrote the \'Harry Potter\' book series?', choices: ['J.K. Rowling', 'Suzanne Collins', 'Rick Riordan', 'C.S. Lewis'], answer: 'J.K. Rowling' },
  { question: 'Which artist is known for cutting off part of his own ear?', choices: ['Vincent van Gogh', 'Paul Gauguin', 'Claude Monet', 'Edvard Munch'], answer: 'Vincent van Gogh' },
  { question: 'Who wrote \'Pride and Prejudice\'?', choices: ['Jane Austen', 'Charlotte Brontë', 'Emily Brontë', 'George Eliot'], answer: 'Jane Austen' },
  { question: 'What is the name of the fictional wizarding school in Harry Potter?', choices: ['Hogwarts', 'Beauxbatons', 'Durmstrang', 'Ilvermorny'], answer: 'Hogwarts' },
  { question: 'Who directed the movies \'Jaws\' and \'E.T.\'?', choices: ['Steven Spielberg', 'George Lucas', 'Martin Scorsese', 'James Cameron'], answer: 'Steven Spielberg' },
  { question: 'What band was John Lennon a member of?', choices: ['The Beatles', 'The Rolling Stones', 'The Who', 'Pink Floyd'], answer: 'The Beatles' },
  { question: 'Who wrote \'1984\' and \'Animal Farm\'?', choices: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'H.G. Wells'], answer: 'George Orwell' },
  { question: 'What is the name of Mickey Mouse\'s pet dog?', choices: ['Pluto', 'Goofy', 'Max', 'Rex'], answer: 'Pluto' },
  { question: 'Who played Iron Man in the Marvel Cinematic Universe?', choices: ['Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'], answer: 'Robert Downey Jr.' },
  { question: 'Which Shakespeare play features the line \'To be or not to be\'?', choices: ['Hamlet', 'Macbeth', 'Othello', 'King Lear'], answer: 'Hamlet' },
  { question: 'Who painted \'Starry Night\'?', choices: ['Vincent van Gogh', 'Claude Monet', 'Paul Cézanne', 'Henri Matisse'], answer: 'Vincent van Gogh' },
  { question: 'Who wrote \'The Adventures of Huckleberry Finn\'?', choices: ['Mark Twain', 'Nathaniel Hawthorne', 'Herman Melville', 'Edgar Allan Poe'], answer: 'Mark Twain' },
  { question: 'What is the fictional continent where most of \'Game of Thrones\' takes place?', choices: ['Westeros', 'Essos', 'Narnia', 'Middle-earth'], answer: 'Westeros' },
  { question: 'Who composed the opera \'The Magic Flute\'?', choices: ['Wolfgang Amadeus Mozart', 'Ludwig van Beethoven', 'Giuseppe Verdi', 'Richard Wagner'], answer: 'Wolfgang Amadeus Mozart' },
  { question: 'What is the highest-grossing film of all time (unadjusted for inflation)?', choices: ['Avatar', 'Titanic', 'Avengers: Endgame', 'Star Wars: The Force Awakens'], answer: 'Avatar' },
  { question: 'Who wrote the Sherlock Holmes detective stories?', choices: ['Arthur Conan Doyle', 'Agatha Christie', 'Wilkie Collins', 'Edgar Allan Poe'], answer: 'Arthur Conan Doyle' },
  { question: 'Which Italian artist sculpted \'David\'?', choices: ['Michelangelo', 'Donatello', 'Bernini', 'Leonardo da Vinci'], answer: 'Michelangelo' },
  { question: 'What is the name of the hobbit who is the main character of \'The Lord of the Rings\'?', choices: ['Frodo Baggins', 'Bilbo Baggins', 'Samwise Gamgee', 'Peregrin Took'], answer: 'Frodo Baggins' },
  { question: 'Who composed the music for \'The Nutcracker\' ballet?', choices: ['Pyotr Ilyich Tchaikovsky', 'Sergei Prokofiev', 'Igor Stravinsky', 'Modest Mussorgsky'], answer: 'Pyotr Ilyich Tchaikovsky' },
  { question: 'What is the name of the coffee shop in the TV show \'Friends\'?', choices: ['Central Perk', 'Java Joe\'s', 'The Coffee Bean', 'Perk Place'], answer: 'Central Perk' },
  { question: 'Who wrote \'The Odyssey\' and \'The Iliad\'?', choices: ['Homer', 'Virgil', 'Sophocles', 'Hesiod'], answer: 'Homer' },
  { question: 'What is the value of pi rounded to two decimal places?', choices: ['3.14', '3.41', '3.12', '3.16'], answer: '3.14' },
  { question: 'How many sides does a hexagon have?', choices: ['6', '5', '7', '8'], answer: '6' },
  { question: 'What is the square root of 64?', choices: ['8', '6', '9', '7'], answer: '8' },
  { question: 'What is the sum of the interior angles of a triangle?', choices: ['180 degrees', '90 degrees', '360 degrees', '270 degrees'], answer: '180 degrees' },
  { question: 'What is the next prime number after 7?', choices: ['11', '9', '13', '10'], answer: '11' },
  { question: 'How many degrees are in a right angle?', choices: ['90', '180', '45', '60'], answer: '90' },
  { question: 'What is 10 factorial divided by 9 factorial (10!/9!)?', choices: ['10', '9', '90', '1'], answer: '10' },
  { question: 'What is the term for a number greater than 1 that can only be divided evenly by 1 and itself?', choices: ['Prime number', 'Composite number', 'Rational number', 'Whole number'], answer: 'Prime number' },
  { question: 'How many sides does a heptagon have?', choices: ['7', '6', '8', '9'], answer: '7' },
  { question: 'What is the Roman numeral for 50?', choices: ['L', 'C', 'D', 'X'], answer: 'L' },
  { question: 'What do you call a triangle with all three sides of equal length?', choices: ['Equilateral triangle', 'Isosceles triangle', 'Scalene triangle', 'Right triangle'], answer: 'Equilateral triangle' },
  { question: 'What is 2 squared plus itself, i.e. the first perfect square greater than 1?', choices: ['4', '2', '9', '1'], answer: '4' },
  { question: 'What is 7 multiplied by 8?', choices: ['56', '54', '64', '49'], answer: '56' },
  { question: 'What do you call a shape with 8 sides?', choices: ['Octagon', 'Hexagon', 'Pentagon', 'Decagon'], answer: 'Octagon' },
  { question: 'How many cards are in a standard deck, excluding jokers?', choices: ['52', '48', '54', '50'], answer: '52' },
  { question: 'How many players are on a standard soccer team on the field at once, per side?', choices: ['11', '10', '9', '12'], answer: '11' },
  { question: 'What is the currency of Japan?', choices: ['Yen', 'Won', 'Yuan', 'Ringgit'], answer: 'Yen' },
  { question: 'How many continents are there in the commonly taught seven-continent model?', choices: ['7', '5', '6', '8'], answer: '7' },
  { question: 'In \'The Hitchhiker\'s Guide to the Galaxy\', the number 42 is the answer to what?', choices: ['Life, the Universe, and Everything', 'The meaning of dreams', 'The speed of light', 'The number of stars in the galaxy'], answer: 'Life, the Universe, and Everything' },
  { question: 'What do you call a polygon with 10 sides?', choices: ['Decagon', 'Nonagon', 'Dodecagon', 'Octagon'], answer: 'Decagon' },
  { question: 'How many minutes are in a full day?', choices: ['1440', '1000', '1200', '24'], answer: '1440' },
  { question: 'What number does the Roman numeral \'C\' represent?', choices: ['100', '50', '500', '1000'], answer: '100' },
  { question: 'How many strings does a standard violin have?', choices: ['4', '5', '6', '3'], answer: '4' },
  { question: 'What do you call an angle greater than 90 but less than 180 degrees?', choices: ['Obtuse angle', 'Acute angle', 'Right angle', 'Reflex angle'], answer: 'Obtuse angle' },
  { question: 'How many days are in a leap year?', choices: ['366', '365', '364', '367'], answer: '366' },
]
